# Generated by Django 5.2.5 on 2025-09-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_remove_employee_compensations_remove_trainee_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='about',
            field=models.CharField(db_index=True, max_length=10000),
        ),
    ]
