# Generated by Django 5.2.5 on 2025-09-09 14:28

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_alter_employee_created'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='hr_employee_created_ix', pages_per_range=2),
        ),
    ]
