# Generated by Django 5.2.5 on 2025-09-24 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+375<operator_code>9999999'.", regex='^\\+375(25|29|33|44)\\d{7}$')]),
        ),
    ]
