name: htmx-books-prod

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    image: django_htmx_prod
    container_name: web_prod
    command: gunicorn django_htmx.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static-data:/home/app/web/static
    env_file:
      - .env.prod
    depends_on:
      - db
      - memcached

  db:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.prod
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

  memcached:
    image: memcached:1.6.21

  nginx:
    build: ./nginx
    volumes:
      - static-data:/home/app/web/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres-data:
  static-data: